language: android

os:
  - linux

android:
  components:
    - build-tools-29.0.2
    - android-29

before_install:
  - chmod +x gradlew

script: ./gradlew check --scan

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  clenup: false
  on:
    branch: master
    tags: true