jobs:
  include:
    - language: android
      os: linux
      android:
        components:
          - build-tools-29.0.2
          - android-29
    - os: osx
      osx_image: xcode11.3

before_install:
  - chmod +x gradlew

script: ./gradlew check --parallel

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload --parallel
  skip_cleanup: true
  on:
    branch: master
    tags: true