language: bash
os: osx
osx_image: xcode11.3

addons:
  homebrew:
    casks:
      - android-sdk

env:
  - ANDROID_SDK_ROOT="/usr/local/share/android-sdk"

before_script:
  - mkdir -p ~/.android && touch ~/.android/repositories.cfg
  - sdkmanager --update
  - yes | sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.2" --license
  - chmod +x gradlew

script: ./gradlew check --parallel --console=plain

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload --parallel --console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true