language: bash
os: osx
osx_image: xcode11.3

addons:
  homebrew:
    casks:
      - android-sdk

env:
  global:
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - JDK="adopt@1.8"
    - ANDROID_SDK_ROOT="/usr/local/share/android-sdk"

before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
  - source ~/.install-jdk-travis.sh

before_script:
  - chmod +x install_android_sdk.sh
  - ./install_android_sdk.sh
  - chmod +x gradlew
  - chmod +x travis_script.sh

script: ./travis_script.sh

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/
    - $TRAVIS_BUILD_DIR/build/firebaseIosSetup
    - $TRAVIS_BUILD_DIR/.gradle

deploy:
  provider: script
  script: ./gradlew bintrayUpload --parallel --console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true
